# Generated by Django 4.2.3 on 2023-07-15 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='members',
            old_name='phone_number',
            new_name='phonenumber',
        ),
    ]
