# Generated by Django 4.2.3 on 2023-07-15 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_phone_number_members_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='college',
            field=models.TextField(default=''),
        ),
    ]
