# Generated by Django 4.2.3 on 2023-07-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_members_college'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='county',
            field=models.TextField(default=''),
        ),
    ]
