# Generated by Django 4.2.3 on 2023-07-16 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_events_gallery_weeklydevotion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='decription',
            field=models.CharField(max_length=300),
        ),
    ]
