# Generated by Django 4.2.3 on 2023-07-18 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_events_decription'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklydevotion',
            name='new',
            field=models.BooleanField(default=True),
        ),
    ]
