# Generated by Django 4.2.3 on 2023-07-18 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_weeklydevotion_new'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name_plural': 'Events'},
        ),
        migrations.AlterModelOptions(
            name='gallery',
            options={'verbose_name_plural': 'Gallery'},
        ),
        migrations.AlterModelOptions(
            name='weeklydevotion',
            options={'verbose_name_plural': 'WeeklyDevotion'},
        ),
    ]
