# Generated by Django 4.2.3 on 2023-07-22 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_events_options_alter_gallery_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='members',
            options={'verbose_name_plural': 'Members'},
        ),
    ]
