# Generated by Django 4.2.3 on 2023-07-22 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_members_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phonenumber',
            field=models.TextField(default='+254'),
        ),
    ]
