# Generated by Django 4.2.3 on 2023-07-22 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_members_phonenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='phonenumber',
            field=models.TextField(default=''),
        ),
    ]
